### ISSUE TITLE
WANTED: James Clark id:26152

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#108]
Quest lacks hand-in dialogue

![Skärmbild från 2021-12-20 18-26-58](https://user-images.githubusercontent.com/29517963/146807666-9a45409c-b978-48ed-83c1-4dfcc5aae0c0.png)
![Skärmbild från 2021-12-20 18-27-00](https://user-images.githubusercontent.com/29517963/146807671-8515aad9-334c-4fc8-9bf3-ed7f8a9e69a8.png)

Quest in Progress:
     Turning in a bounty?
     
Quest Completion:
     And justice is served!
     
https://www.wowhead.com/npc=42256/marshal-patterson

**Comment by CWSturm** [comment]
Fixed.
