### ISSUE TITLE
Hero's Call: Westfall! id:28562

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#111]
Similar to #110. Quest lacks hand-in text. 

Should be:
Murder, rookie. That's what you're looking at on the ground in front of us.

https://www.wowhead.com/quest=28562/heros-call-westfall
![Skärmbild från 2021-12-20 19-16-04](https://user-images.githubusercontent.com/29517963/146813866-5e24f87e-28cc-4943-bab5-71cf77b20486.png)

**Comment by CWSturm** [comment]
Fixed.
