### ISSUE TITLE
Invasion id:14321

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#132]
When the quest is picked up, the Forsaken Assassin that spawns should say "Gilneas will soon belong to the Forsaken!" and immediately attack the player. The assassin should also cast Backstab (75360).

https://www.wowhead.com/quest=14321/invasion
https://www.wowhead.com/npc=36207/forsaken-assassin#abilities
https://www.wowhead.com/spell=75360/backstab

**Comment by CWSturm** [comment]
Fix applied.
