### ISSUE TITLE
[quest] Vile and Tainted id:26690

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#140]
Missing Completion quest text

_<name>, to be honest with you, I did not believe that you would get this far, but you are clearly a <class> to be reckoned with. In fact, if you wish to formally join Master Carevin's struggle, I will gladly write for you a letter of recommendation._

https://www.wowhead.com/quest=26690/vile-and-tainted

**Comment by CWSturm** [comment]
Fix applied.
