### ISSUE TITLE
[quest] Mistmantle's Revenege id:26674

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#142]
Missing quest completion text 

_Master Harris may have been right. I would have been better to leave the past behind.

I've got a new life now. Whether it's that of a monster or a man is up to me.

As for you, I cannot thank you enough for your assistance, regardless of the outcome. Please, take this with my thanks._

https://www.wowhead.com/quest=26674/mistmantles-revenge

**Comment by CWSturm** [comment]
Fixed.
