### ISSUE TITLE
[quest] Hero's Call: Redridge Mountains! id:28563 

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#148]
Missing completion text

_Heard Westfall was in some deep doody.

<Parker doesn't even turn to face you.>

Well, we got our own set of problems here. See them gnolls out there? Looks like they're actin' up again. I don't like it. Don't like it one bit._

https://www.wowhead.com/quest=26365/heros-call-redridge-mountains

**Comment by CWSturm** [comment]
Fix applied.
