### ISSUE TITLE
[quest] Still Assessing the threat id: 26503

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#156]
missing completion quest text

_ knew it! Looks like Yowler is behind this uprising - which is incredible, because we keep killing gnolls named Yowler. I don't know how many sons the original Yowler had, but it's got to be close to a hundred.

Well, looks like we got ourselves another Yowler to kill.

Magistrate Solomon must be notified._

https://www.wowhead.com/quest=26503/still-assessing-the-threat

**Comment by CWSturm** [comment]
Fix applied.
