### ISSUE TITLE
[quest[ Parker's report id: 26505

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#158]
missing completion text 

_<Magistrate Solomon puts on his monocle.>

Oh, you're not Conacher. What have you got there?

<Magistrate Solomon takes Parker's report from you.>

Oh for pity's sake. Yowler? AGAIN?_ 

https://www.wowhead.com/quest=26505/parkers-report

**Comment by CWSturm** [comment]
Fix applied.
