### ISSUE TITLE
Duskhaven Watchman id:36690

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#165]
Duplicate NPCs standing inside eachother
![Skärmbild från 2021-12-21 14-19-07](https://user-images.githubusercontent.com/29517963/146936853-a8d4587d-9760-4dec-9a2d-34c3662749e4.png)
![Skärmbild från 2021-12-21 14-20-53](https://user-images.githubusercontent.com/29517963/146936856-c537a7db-2fbc-4f02-b792-716f9513dbbf.png)
![Skärmbild från 2021-12-21 14-20-57](https://user-images.githubusercontent.com/29517963/146936857-86a48bc3-2a96-4bb6-9ca7-2938a015e4fc.png)
![Skärmbild från 2021-12-21 14-21-02](https://user-images.githubusercontent.com/29517963/146936863-f9371b8a-757e-40f9-9dbf-71e7ea00b3d7.png)

https://www.wowhead.com/npc=36690/duskhaven-watchman#abilities

**Comment by CWSturm** [comment]
Duplicates removed.
