### ISSUE TITLE
[quest] Surveying Equipment id:26569 

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#180]
missing completion quest 
_Fantastic work, <name>! These will come in handy for our next project, the Lakeshire SUPER BRIDGE, meant to traverse the length of Lake Everstill. It should be done in 20 or so years. Give or take a decade or two._
https://www.wowhead.com/quest=26569/surveying-equipment

**Comment by CWSturm** [comment]
Fix applied.
