### ISSUE TITLE
[quest] Canyon Romp id:26514

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#181]
missing completion text
_<The gnomecorder crackles and pops.>

Good work, <name>. I've just been handed some important information. It would appear that our most hated enemy, the Blackrock orcs, have wised up...

I've transferred a few silver over to you for the gnome, erm, gnoll kills._
https://www.wowhead.com/quest=26514/canyon-romp

**Comment by CWSturm** [comment]
Fix applied.
