### ISSUE TITLE
[quest[ return of the bravo company id:26563

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#187]
missing completion text
_
Unbelievable work, <name>. You've managed to rescue the entire Bravo Company from the clutches of the Blackrock orcs? With Keeshan's team rescued and Keeshan's belongings returned, there's no way Keeshan could refuse us._
https://www.wowhead.com/quest=26563/return-of-the-bravo-company

**Comment by CWSturm** [comment]
Fix applied.
