### ISSUE TITLE
[quest] Weapons of war id:26571

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#188]
missing completion text
_<The gnomecorder buzzes with energy.>

Come in, <name>. Do you copy? Troteman here! Great job on getting Keeshan's weapons back! Now there's one final mission you have to run. Are you up to the challenge?_
https://www.wowhead.com/quest=26571/weapons-of-war

**Comment by CWSturm** [comment]
Fix applied.
