### ISSUE TITLE
[quest] They Drew first blood id:26607

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#191]
missing completion text
_<Keeshan takes the bundle from you and opens it.>

My bow... and knife! Where did you...

Jade's amulet... My darling Jade.

<Keeshan picks up his red headband.>

We got orcs to kill._
https://www.wowhead.com/quest=26607/they-drew-first-blood

**Comment by CWSturm** [comment]
Fix applied.
