### ISSUE TITLE
[quest] unspeakable atrocities id:26640

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#209]
missing completion text
_<Keeshan reads the report.>

DAMN IT! This just got complicated. We've got prisoners of war to rescue before we can blow up the valley. Not to mention the orcs have black dragons on their side.

Are you ready, <name>?_
https://www.wowhead.com/quest=26640/unspeakable-atrocities

**Comment by CWSturm** [comment]
Fixed.
