### ISSUE TITLE
[Quest} Bravo company Field kit: Chloroform id:26637

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#210]
missing completion quest text 
_Perfect. Those orcs won't know what hit 'em - literally. I'll need a few minutes to get these in working order and then I'll put them in the Bravo Company field kit._
https://www.wowhead.com/quest=26637/bravo-company-field-kit-chloroform

**Comment by CWSturm** [comment]
Fixed.
