### ISSUE TITLE
[quest] They've Wised Up... id:26544 

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#214]
missing completion text
_<The gnomecorder buzzes and whirs.>
Just put the missive in the little compartment and I'll read it. I am fluent in orcish.
<You hear a distraught yell in the background.>
It looks like these orcs are here under the direct command of Yowler. That means Yowler must have the orc invasion plan._
https://www.wowhead.com/quest=26544/theyve-wised-up

**Comment by CWSturm** [comment]
Fixed.
