### ISSUE TITLE
Off to the Bank id:26711, 26712

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#217]
Missing quest completion text.

If player has the female version of the quest

> Oh, it's you, ma'am! Sorry, I didn't recognize you at first with all of these commoners milling about.
> 
> You people cool your heels! PlayerName is here!
> 
> Here are your macaroons, ma'am. Come back anytime if you need more.

If player has the male version of the quest

> Oh, it's you, sir! Sorry, I didn't recognize you at first with all of these commoners milling about.
> 
> You people cool your heels! PlayerName is here!
> 
> Here are your macaroons, sir. Come back anytime if you need more.

https://www.wowhead.com/quest=26711/off-to-the-bank (Female Goblin version)
https://www.wowhead.com/quest=26712/off-to-the-bank (Male Goblin version)

**Comment by CWSturm** [comment]
Unable to reproduce.
