### ISSUE TITLE
Wayward Fire Elemental id:37112

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#253]
When aggroed, the elemental should yell:

> Wayward Fire Elemental: [Kalimag] T MA TORO NUK KRAST'VEN FMERK

Which basically translates into 
>    [Kalimag] I AM FROM THE ELEMENTAL PLANE!

https://www.wowhead.com/npc=37112/wayward-fire-elemental#comments

**Comment by CWSturm** [comment]
Fix applied.
