### ISSUE TITLE
Issue when dying

### ISSUE THREAD

**Issue by silverlego** [XayeCW/Celestial-wow-Issues#26]
when I died in ragefire chasm I released my spirit and ended  up next to the spirit healer, the spirit healer did not give me the option to res with res sick, it just had text but no res button so I had to walk back.

**Comment by arft1kwerg** [comment]
This affects many other areas. When interacting with Spirit Healers they only have gossip text. None of them offer the player the ability to resurrect at the graveyard. 

Spirit Healer NPC id: 6491
![Skärmbild från 2021-12-20 18-52-26](https://user-images.githubusercontent.com/29517963/146810843-67f21695-5b39-445b-803c-92248b54df17.png)

https://web.archive.org/web/20180124064954/https://www.wowhead.com/npc=6491/spirit-healer

**Comment by arft1kwerg** [comment]
Should fix Spirit Healers
`UPDATE creature_template SET npcflag = 16384 WHERE entry = 6491;`

**Comment by CWSturm** [comment]
Good suggestion. But, It seems we would need to do this instead: UPDATE creature_template SET npcflag = 16384 WHERE subname = "Spirit Healer";

**Comment by arft1kwerg** [comment]
After the sql fix was applied. Players can now resurrect at GYs by speaking to Spirit Healers.
