### ISSUE TITLE
Mountaineer Valgrum id:41056

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#265]
Lacks faction tag. Should be Ironforge (id:47).

https://www.wowhead.com/npc=41056/mountaineer-valgrum#comments

**Comment by arft1kwerg** [comment]
Should fix the issue:

`UPDATE creature_template SET faction = 55 WHERE entry = 41056;`

**Comment by Greaver** [comment]
55? should it be 47 ( Ironforge )?

**Comment by arft1kwerg** [comment]
> 55? should it be 47 ( Ironforge )?

It's because it's a reference to the reputation and behaviour table. While 47 is indeed the reputation ID of the faction, in the reputation table the NPCs should be set to generic non-fighting Ironforge, which has the table ID of 55

**Comment by arft1kwerg** [comment]
Has correct faction tag now
