### ISSUE TITLE
Forced to Watch from Afar id:313

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#266]
When speaking to the NPCs and selecting their gossip option, they don't respond with their respective quotes.

>    Mountaineer Dunstan says: Tell Captain Tharran that I'll be back in Kharanos as soon as I've verified that the bot is working correctly.

>    Mountaineer Lewin says: I can't wait to get out there and help in the fight against those trolls.

>    Mountaineer Valgrum says: We've been fighting nonstop since the cataclysm. It'll be nice to get a rest, if a brief one.

https://www.wowhead.com/quest=313/forced-to-watch-from-afar
https://www.wowhead.com/npc=40991/mountaineer-dunstan
https://www.wowhead.com/npc=40994/mountaineer-lewin
https://www.wowhead.com/npc=41056/mountaineer-valgrum

**Comment by CWSturm** [comment]
Fix applied. ( From Nero's stash, modified from Cata to Legion format. )
