### ISSUE TITLE
Scuttling Mechano-Tank id:39716

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#268]
NPC was removed in patch 4.0.1. Players can enter the vehicle without being on the quest One Step Forward... which was removed together with the entire Operation: Gnomeregan chain.

https://www.wowhead.com/quest=25289/
https://www.wowhead.com/npc=39716/scuttling-mechano-tank#comments

**Comment by CWSturm** [comment]
Removed.
