### ISSUE TITLE
Get to the Airfield id:25998

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#283]
Missing quest completion text.

Commander Stonebreaker should have the hand-in text:

> Thank goodness you're here, PlayerName. The airfield's been attacked by the Dark Irons and I don't think we can hold out much longer.

https://www.wowhead.com/quest=25998/get-to-the-airfield
https://www.wowhead.com/npc=41853/commander-stonebreaker

**Comment by CWSturm** [comment]
Fixed.
