### ISSUE TITLE
Extinguish the Fires id:26078

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#285]
Lacks quest completion text.

Commander Stonebreaker text should be:
> Well done! My men are working hard on getting our flying machines and steam tanks back into the fight.

https://www.wowhead.com/quest=26078/extinguish-the-fires
https://www.wowhead.com/npc=41853/commander-stonebreaker

**Comment by CWSturm** [comment]
Fixed.
