### ISSUE TITLE
Rallying the Defenders id:26085

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#287]
Lacks quest completion text.

Commander Stonebreaker text should be:

> The men are finding hidden reserves of strength and courage to deal with the Dark Iron onslaught. The airfield will not fall on our watch!

https://www.wowhead.com/quest=26085/rallying-the-defenders
https://www.wowhead.com/npc=41853/commander-stonebreaker

**Comment by CWSturm** [comment]
Fixed.
