### ISSUE TITLE
Striking Back id:26094

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#288]
Lacks quest completion text.

Commander Stonebreaker text should be:

> The momentum is starting to shift, PlayerName, largely due to your efforts. Now, it is time to strike at the Dark Iron leadership.

https://www.wowhead.com/quest=26094/striking-back#comments
https://www.wowhead.com/npc=41853/commander-stonebreaker

**Comment by CWSturm** [comment]
Fixed.
