### ISSUE TITLE
[Bayne:10356] Triple** Rare spawn

### ISSUE THREAD

**Issue by SilverAsh00** [XayeCW/Celestial-wow-Issues#296]
I just killed one, confirmed all's good, i turn around, and there's another one lul.
****UPDATE There's a third one not too far from the other 2. @Last image

![image](https://user-images.githubusercontent.com/88670869/147216000-90800290-931a-48c0-a863-d94bb95829b1.png)
![image](https://user-images.githubusercontent.com/88670869/147217243-57e2fbb3-fb69-4563-9aa9-626242e82c77.png)

**Comment by CWSturm** [comment]
Excessive spawns removed.
