### ISSUE TITLE
Reinforcements for Loch Modan id:26131

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#309]
Gryth Thurden's quest specific gossip option "Mountaineer Barleybrew said you could help me get to Loch Modan." doesn't do anything when selected. It should send the player on a one way trip to South Gate Pass and land the player in front of Pilot Hammerfoot.

https://www.youtube.com/watch?v=nGvQxs7rdks
https://www.wowhead.com/quest=26131/reinforcements-for-loch-modan
https://www.wowhead.com/npc=1573/gryth-thurden#comments
https://www.wowhead.com/npc=1960/pilot-hammerfoot

**Comment by CWSturm** [comment]
Fix applied.
