### ISSUE TITLE
[warlock][destruction] Soul Shard fragments

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#34]
All abilities that are supposed to generate Soul Shard Fragments (10 Fragments = 1 Soul Shard), are instead restoring full Soul Shards. Conflagration for example should generate 5 fragments meaning 2 Conflags = 1 Soul Shard, but it is instead filling 5 Soul Shards. This affects all Soul Shard Fragment generating spells (Immolate, Conflagrate, Incinerate) and leads to ridiculous Soul Shard generation rate.
![Skärmbild från 2021-12-19 19-26-09](https://user-images.githubusercontent.com/29517963/146686470-6cdd2172-faa1-4783-b8ef-55c3ff5e6160.png)
![Skärmbild från 2021-12-19 19-26-11](https://user-images.githubusercontent.com/29517963/146686473-8cae9416-1b53-42b7-84c1-5b442e2535b2.png)

**Comment by CWSturm** [comment]
Fix applied.
