### ISSUE TITLE
[Warlock][Demonology] Soul Shards id:246985

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#37]
Soul Shards do not regenerate outside of combat for Demonology Warlocks. Should generate up to 3 like the other Warlock specs.
![Skärmbild från 2021-12-19 19-44-46](https://user-images.githubusercontent.com/29517963/146686992-d2d045b8-3956-4a2c-afb4-0a9286ebd577.png)

**Comment by CWSturm** [comment]
Does it work otherwise, as in shards appear on your ui at lvl(3)?

**Comment by arft1kwerg** [comment]
Nope, they don't show up at all.
![Skärmbild från 2021-12-19 19-53-11](https://user-images.githubusercontent.com/29517963/146687294-9d2ea637-7bf2-4c52-a941-db4ae0c88e5e.png)
![Skärmbild från 2021-12-19 19-56-58](https://user-images.githubusercontent.com/29517963/146687295-1fc56ef2-4b37-49bd-9fd3-73b93ec638c6.png)

**Comment by arft1kwerg** [comment]
Soul Shards only show up when you hit level 10 Before that every level up dismisses your imp, and you cannot regenerate Soul Shards. Summoning an imp still costs Shards

**Comment by arft1kwerg** [comment]
![Skärmbild från 2021-12-19 20-00-29](https://user-images.githubusercontent.com/29517963/146687363-85f64eee-a3bc-4695-be38-8edeaa1d6a82.png)

**Comment by CWSturm** [comment]
Pretty sure this is now working as intended, the UI should only show up at lvl 10 after selecting a specialization. Shards will generate in the backround nevertheless.
