### ISSUE TITLE
Saving Princess Stillpine id:9667

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#404]
After opening the cage that Princess Stillpine is stuck in, she should turn untargetable and say:

Princess Stillpine says: Thank you for saving me, PlayerName! My father will be delighted!

After which she should run away towards the beach and despawn

https://www.wowhead.com/quest=9667/saving-princess-stillpine
https://www.wowhead.com/npc=17682/princess-stillpine

**Comment by CWSturm** [comment]
Fix applied.
