### ISSUE TITLE
Catch and Release id:9629

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#415]
Tagging a Blacksilt Murloc with the Murloc Tagger doesn't increase the quest completion counter, making it impossible to complete.

![Skärmbild från 2021-12-28 01-23-37](https://user-images.githubusercontent.com/29517963/147515342-6672fcb9-44e2-40d3-a275-8dca793f6425.png)

https://www.wowhead.com/quest=9629/catch-and-release
https://www.wowhead.com/item=23995/murloc-tagger
https://www.wowhead.com/npc=17654/tagged-blacksilt-scout
https://www.wowhead.com/spell=30877/tag-murloc

**Comment by CWSturm** [comment]
Fix applied.
