### ISSUE TITLE
What We Don't Know... id:9756

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#416]
The final gossip dialogue option does nothing when clicked. Rending the quest uncompletable. 

Gossip option: I did and you believed me. Thank you for the information, blood elf. You have helped us more than you could know.

Upon pressing that option. The dialogue should end, the quest marked as complete, and the Captured Sunhawk Agent should say:

Captured Sunhawk Agent says: Treacherous whelp! Sironas will destroy you and your people! 

https://www.wowhead.com/quest=9756/what-we-dont-know#comments
https://www.wowhead.com/npc=17824/captured-sunhawk-agent#comments

**Comment by CWSturm** [comment]
Fix applied, working as intended.
