### ISSUE TITLE
[hunter][spell] Disengage

### ISSUE THREAD

**Issue by Duckhugs** [XayeCW/Celestial-wow-Issues#44]
Disengage Is missing from the Hunter Spellbook 
![WoWScrnShot_121921_120814](https://user-images.githubusercontent.com/96391480/146689315-9dcad2bf-1508-4a64-a80f-1cb5e628d6ad.jpg)
 
edit: just got it at level 20, could have been me misremembering something my bad if so.

**Comment by CWSturm** [comment]
Invalid report :)
