### ISSUE TITLE
Gasping for Breath (Quest #14395) objective not registering

### ISSUE THREAD

**Issue by Ghost49X** [XayeCW/Celestial-wow-Issues#445]
This is a complicated quest in a buggy way...
The npcs (NPC #36440) you're supposed to save don't always properly give you the buff (Spell #68735) and start the carry animation when you right-click them.
Once you do get one, getting to shore doesn't properly register you saving the npc (NPC #36440) from drowing preventing you from completing the objective.

I've tried moving around on the coast and talking to the quest giver but nothing registers the objective.

As this quest is required to progress the story, fixing it should be set at a higher priority.

**Comment by CWSturm** [comment]
Duplicate issue
