### ISSUE TITLE
Evelyn forest 1-10 human

### ISSUE THREAD

**Issue by PurplePath** [XayeCW/Celestial-wow-Issues#7]
[evelyn forest.txt](https://github.com/XayeCW/Celestial-wow-Issues/files/7739497/evelyn.forest.txt)

**Comment by CWSturm** [comment]
Please make a report for every issue individually, you will get more rewards that way.

**Comment by PurplePath** [comment]
Did it want to organize it better for your benefit but ok I will do it One
by one for the next I found
