### ISSUE TITLE
Rest and Relaxation id:37112

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#88]
Missing hand-in text. Should be:

> Rest and relaxation for the tired and cold -- that's our motto! Please, take a seat by the fire and rest your weary bones.
> 
> Would you like to try a sampling of some of our fine food and drink?

![Skärmbild från 2021-12-20 16-37-19](https://user-images.githubusercontent.com/29517963/146793252-2f6568c6-6291-495d-a6f4-f30b6a117a0d.png)
![Skärmbild från 2021-12-20 16-38-05](https://user-images.githubusercontent.com/29517963/146793255-51c5c729-4b10-42ee-b954-777429ebb630.png)
Subscription thing is just a screen glitch on my side, ignore it.

https://www.wowhead.com/quest=37112/rest-and-relaxation#comments

**Comment by CWSturm** [comment]
Fixed.
