### ISSUE TITLE
Red Dragon Turtle id:65065

### ISSUE THREAD

**Issue by arft1kwerg** [XayeCW/Celestial-wow-Issues#97]
This Red Dragon Turtle near the Stormwind City Earthshrine is floating in the air. Should idle on the ground.
![Skärmbild från 2021-12-20 17-24-57](https://user-images.githubusercontent.com/29517963/146799889-085aae20-530d-45c8-9544-dd63e92e779a.png)

**Comment by CWSturm** [comment]
Poor thing has been deflated and is now firmly on the ground.
